*  530
*  Weeks 1 & 2
*  David Jorgensen

# Chapter 3, Exercise 1
We want to look at data for the Facebook, Apple, Amazon, Netflix, and Google (FAANG) stocks, but we were given each as a separate CSV file (obtained using the stock_analysis package we will build in Chapter 7, Financial Analysis – Bitcoin and the Stock Market). Combine them into a single file and store the dataframe of the FAANG data as faang for the rest of the exercises:
- Read in the `aapl.csv`, `amzn.csv`, `fb.csv`, `goog.csv`, and `nflx.csv` files.
- Add a column to each dataframe, called ticker, indicating the ticker symbol it is for (Apple's is AAPL, for example); this is how you look up a stock. In this case, the filenames happen to be the ticker symbols.
- Append them together into a single dataframe.
- Save the result in a CSV file called `faang.csv`

In [ ]:
# Read in the aapl.csv, amzn.csv, fb.csv, goog.csv, and nflx.csv files
import pandas as pd
aapl = pd.read_csv('textbook/ch_03/exercises/aapl.csv')
amzn = pd.read_csv('textbook/ch_03/exercises/amzn.csv')
fb = pd.read_csv('textbook/ch_03/exercises/fb.csv')
goog = pd.read_csv('textbook/ch_03/exercises/goog.csv')
nflx = pd.read_csv('textbook/ch_03/exercises/nflx.csv')

In [ ]:
# Add ticker columns to each dataframe
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'
nflx['ticker'] = 'NFLX'

In [ ]:
# Append stock tables together into a single dataframe
stocks = pd.concat([aapl, amzn, fb, goog, nflx], ignore_index=True)

In [ ]:
# Save the result in a CSV file
stocks.to_csv('faang.csv', index=False)

# Chapter 3, Exercise 2
With faang, use type conversion to cast the values of the date column into datetimes and the volume column into integers. Then, sort by date and ticker.

In [ ]:
# Cast the values of the date column into datetimes and the volume column into integers
stocks['date'] = pd.to_datetime(stocks['date'])
stocks['volume'] = stocks['volume'].astype(int)

In [6]:
# sort by date and ticker
stocks = stocks.sort_values(by=['date', 'ticker'])
stocks.reset_index(drop=True, inplace=True)
stocks

,date,high,low,open,close,volume,ticker
0,2018-01-02,43.075001,42.314999,42.540001,43.064999,102223600,AAPL
1,2018-01-02,1190.000000,1170.510010,1172.000000,1189.010010,2694500,AMZN
2,2018-01-02,181.580002,177.550003,177.679993,181.419998,18151900,FB
3,2018-01-02,1066.939941,1045.229980,1048.339966,1065.000000,1237600,GOOG
4,2018-01-02,201.649994,195.419998,196.100006,201.070007,10966900,NFLX
...,...,...,...,...,...,...,...
1250,2018-12-31,39.840000,39.119999,39.632500,39.435001,140014000,AAPL
1251,2018-12-31,1520.760010,1487.000000,1510.800049,1501.969971,6954500,AMZN
1252,2018-12-31,134.639999,129.949997,134.449997,131.089996,24625300,FB
1253,2018-12-31,1052.699951,1023.590027,1050.959961,1035.609985,1493300,GOOG
1254,2018-12-31,270.100006,260.000000,260.160004,267.660004,13508900,NFLX

# Chapter 3, Exercise 3
Find the seven rows in faang with the lowest value for volume.

In [ ]:
# Find the seven rows with the lowest value for volume
stocks.nsmallest(7, 'volume')

,date,high,low,open,close,volume,ticker
633,2018-07-03,1135.819946,1100.020020,1135.819946,1102.890015,679000,GOOG
1133,2018-11-23,1037.589966,1022.398987,1030.000000,1023.880005,691500,GOOG
498,2018-05-24,1080.469971,1066.150024,1079.000000,1079.239990,766800,GOOG
653,2018-07-10,1159.589966,1149.589966,1156.979980,1152.839966,798400,GOOG
763,2018-08-09,1255.541992,1246.010010,1249.900024,1249.099976,848600,GOOG
798,2018-08-20,1211.000000,1194.625977,1205.020020,1207.770020,870800,GOOG
808,2018-08-22,1211.839966,1199.000000,1200.000000,1207.329956,887400,GOOG

# Chapter 3, Exercise 4
Right now, the data is somewhere between long and wide format. Use `melt()` to make it completely long format. *Hint: date and ticker are our ID variables (they uniquely identify each row). We need to melt the rest so that we don't have separate columns for open, high, low, close, and volume.*

In [ ]:
# Convert data to long format
long_stocks = pd.melt(stocks, id_vars=['date', 'ticker'], var_name='variable', value_name='value')
long_stocks

           date ticker variable         value
0    2018-01-02   AAPL     high  4.307500e+01
1    2018-01-02   AMZN     high  1.190000e+03
2    2018-01-02     FB     high  1.815800e+02
3    2018-01-02   GOOG     high  1.066940e+03
4    2018-01-02   NFLX     high  2.016500e+02
...         ...    ...      ...           ...
6270 2018-12-31   AAPL   volume  1.400140e+08
6271 2018-12-31   AMZN   volume  6.954500e+06
6272 2018-12-31     FB   volume  2.462530e+07
6273 2018-12-31   GOOG   volume  1.493300e+06
6274 2018-12-31   NFLX   volume  1.350890e+07

[6275 rows x 4 columns]

# Chapter 3, Exercise 5
Suppose we found out that on July 26, 2018 there was a glitch in how the data was recorded. How should we handle this? Note that there is no coding required for this exercise.

A: I'd start with verifying the scope of the glitch: pinpoint the exact days and variables affected, and check if the glitch is isolated or systemic. Next, I'd verify against external sources such as Bloomberg or Nasdaq to see if any data can be recovered. If no reliable replacement data exists, I'd probably use exclusion and remove the affected day since it's a small portion of the dataset. But if the affected portion is large, I might opt for imputation, likely interpolation, so that the overall stock valuation trend spanning July 26-28 is preserved.

# Chapter 3, Exercise 6
[The European Centre for Disease Prevention and Control (ECDC)](https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide) provides an open dataset on COVID-19 cases called daily number of new reported cases of COVID-19 by country worldwide. This dataset is updated daily, but we will use a snapshot that contains data from January 1, 2020 through September 18, 2020. Clean and pivot the data so that it is in wide format:
- Read in the *covid19\_cases.csv* file.
- Create a date column using the data in the *dateRep* column and the *pd.to\_datetime()* function.
- Set the date column as the index and sort the index.
- Replace all occurrences of *United\_States\_of\_America* and *United\_Kingdom* with *USA* and *UK*, respectively. Hint: the replace() method can be run on the dataframe as a whole.
- Using the *countriesAndTerritories* column, filter the cleaned COVID-19 cases data down to Argentina, Brazil, China, Colombia, India, Italy, Mexico, Peru, Russia, Spain, Turkey, the UK, and the USA.
- Pivot the data so that the index contains the dates, the columns contain the country names, and the values are the case counts (the *cases* column). Be sure to fill in NaN values with 0.

In [9]:
# Read in the covid19_cases.csv file
covid19 = pd.read_csv('textbook/ch_03/exercises/covid19_cases.csv')
covid19_total = pd.read_csv('textbook/ch_03/exercises/covid19_total_cases.csv')

In [ ]:
# Create a date column in covid19
covid19['date'] = pd.to_datetime(covid19['dateRep'], format='%d/%m/%Y')

In [11]:
# Set the date column as the index and sort the index
covid19.set_index('date', inplace=True)
covid19 = covid19.sort_index()

In [ ]:
# Replace all occurrences of United_States_of_America and United_Kingdom with USA and UK
covid19['countriesAndTerritories'] = covid19['countriesAndTerritories'].replace({
    'United_States_of_America': 'USA',
    'United_Kingdom': 'UK'
})

In [ ]:
# Filter the cleaned COVID-19 cases data down to Argentina, Brazil, China, Colombia, India, Italy, Mexico, Peru, Russia, Spain, Turkey, the UK, and the USA
countries = ['Argentina', 'Brazil', 'China', 'Colombia', 'India', 'Italy', 'Mexico', 'Peru', 'Russia', 'Spain', 'Turkey', 'UK', 'USA']
filtered_covid19 = covid19[covid19['countriesAndTerritories'].isin(countries)]

In [ ]:
# Pivot the data
pivoted_covid19 = filtered_covid19.pivot_table(
    index=filtered_covid19.index, # dates are the index
    columns='countriesAndTerritories', # country names are the columns
    values='cases', # values are from the cases column
    aggfunc='sum', # in case there are multiple entries for the same date and country, sum them
    fill_value=0 # replace NaN values with 0
)
pivoted_covid19

countriesAndTerritories,Argentina,Brazil,China,Colombia,India,Italy,Mexico,Peru,Russia,Spain,Turkey,UK,USA
date,,,,,,,,,,,,,
2020-01-01,0,0,0,0,0,0,0,0,0,0,0,0,0
2020-01-02,0,0,0,0,0,0,0,0,0,0,0,0,0
2020-01-03,0,0,17,0,0,0,0,0,0,0,0,0,0
2020-01-04,0,0,0,0,0,0,0,0,0,0,0,0,0
2020-01-05,0,0,15,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-14,10778,14768,29,7355,92071,1456,4408,6787,5449,27404,1527,3330,33871
2020-09-15,9056,15155,22,5573,83809,1008,3335,4241,5509,9437,1716,2621,34841
2020-09-16,9908,36653,24,6698,90123,1229,4771,4160,5529,11193,1742,3103,51473
2020-09-17,11893,36820,7,7787,97894,1452,4444,6380,5670,11291,1771,3991,24598
2020-09-18,11674,36303,44,7568,96424,1583,3182,5698,5762,14389,1648,3395,43567